name: Build book and Archive

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: gengjiawen/gitbook:1.0.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build books
        run: |
          mkdir dist
          gitbook epub ./ dist/investment.epub
          gitbook epub ./ dist/investment.epub
          ebook-convert dist/investment.epub dist/investment.pdf
          ls -lh -R dist
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: books
          path: |
            dist
            !dist/**/*.md