name: Release book

on:
  push:
    tags:
      - '*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: gengjiawen/gitbook:1.0.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build books
        run: |
          mkdir dist
          gitbook epub ./ dist/investment.epub
          gitbook epub ./ dist/investment.epub
          ebook-convert dist/investment.epub dist/investment.pdf
          ls -lh -R dist
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/investment.epub
            dist/investment.pdf
          